# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[changelog]
# Changelog header
header = """
# Changelog\n
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n
"""
# Template for the changelog body
# https://keats.github.io/tera/docs/#introduction
body = """
{%- macro remote_url() -%}
  https://github.com/your-org/your-repo
{%- endmacro -%}

{% if version -%}
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
    ## [Unreleased]
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits
    | filter(attribute="scope")
    | sort(attribute="scope") %}
        - **{{ commit.scope }}:** {{ commit.message | upper_first }}
            {%- if commit.breaking %} [**BREAKING**]{% endif -%}
            {%- if commit.body %}\n\n            {{ commit.body | indent(width=12) }}{% endif %}
            ([{{ commit.id | truncate(length=7, end="") }}]({{ self::remote_url() }}/commit/{{ commit.id }}))
    {%- endfor -%}
    {% for commit in commits %}
        {%- if not commit.scope -%}
        - {{ commit.message | upper_first }}
            {%- if commit.breaking %} [**BREAKING**]{% endif -%}
            {%- if commit.body %}\n\n            {{ commit.body | indent(width=12) }}{% endif %}
            ([{{ commit.id | truncate(length=7, end="") }}]({{ self::remote_url() }}/commit/{{ commit.id }}))
        {% endif -%}
    {% endfor -%}
{% endfor %}
"""
# Template for the changelog footer
footer = """
---
{% for release in releases -%}
    {% if release.version -%}
        {% if release.previous.version -%}
            [{{ release.version | trim_start_matches(pat="v") }}]: \
                https://github.com/your-org/your-repo/compare/{{ release.previous.version }}..{{ release.version }}
        {% endif -%}
    {% else -%}
        [Unreleased]: https://github.com/your-org/your-repo/compare/{{ release.previous.version }}..HEAD
    {% endif -%}
{% endfor %}
"""
# Remove leading and trailing whitespace from the templates
trim = true

[git]
# Parse the commits based on https://www.conventionalcommits.org
conventional_commits = true
# Filter out the commits that are not conventional
filter_unconventional = true
# Process each line of a commit as an individual commit
split_commits = false
# Regex for preprocessing the commit messages
commit_preprocessors = [
    # Replace issue numbers with links
    { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](https://github.com/your-org/your-repo/issues/${2}))" },
    # Remove gitmoji
    { pattern = '[\u{1f300}-\u{1f9ff}]', replace = "" },
    # Check spelling of the commit with https://github.com/crate-ci/typos
    # { pattern = '.*', replace_command = 'typos --write-changes -' },
]
# Regex for parsing and grouping commits
commit_parsers = [
    { message = "^feat",     group = "<!-- 0 -->ğŸš€ Features" },
    { message = "^fix",      group = "<!-- 1 -->ğŸ› Bug Fixes" },
    { message = "^perf",     group = "<!-- 2 -->âš¡ Performance" },
    { message = "^refactor", group = "<!-- 3 -->ğŸ”¨ Refactor" },
    { message = "^doc",      group = "<!-- 4 -->ğŸ“š Documentation" },
    { message = "^style",    group = "<!-- 5 -->ğŸ¨ Styling" },
    { message = "^test",     group = "<!-- 6 -->ğŸ§ª Testing" },
    { message = "^ci",       group = "<!-- 7 -->âš™ï¸ CI/CD" },
    { message = "^build",    group = "<!-- 7 -->âš™ï¸ CI/CD" },
    { message = "^chore\\(release\\):", skip = true },
    { message = "^chore\\(deps.*\\)", skip = true },
    { message = "^chore\\(pr\\)",     skip = true },
    { message = "^chore\\(pull\\)",   skip = true },
    { message = "^chore|^ci",  group = "<!-- 8 -->ğŸ”§ Miscellaneous Tasks" },
    { body    = ".*security",  group = "<!-- 9 -->ğŸ”’ Security" },
    { message = "^revert",    group = "<!-- 10 -->â—€ï¸ Reverts" },
]
# Protect breaking changes from being skipped due to matching a skipping commit_parser
protect_breaking_commits = true
# Filter out the commits that are not matched by commit parsers
filter_commits = false
# Tag pattern regex
tag_pattern = "v[0-9].*"
# Regex for skipping tags
skip_tags = "beta|alpha"
# Regex for ignoring tags
ignore_tags = "rc"
# Sort the tags topologically
topo_order = false
# Sort the commits inside sections by oldest/newest order
sort_commits = "oldest"
# Limit the number of commits included in the changelog
# limit_commits = 42

[remote.github]
owner = "your-org"
repo  = "your-repo"
# token = ""  # Set via GITHUB_TOKEN env var
